# Generated by Django 2.2.10 on 2020-02-08 18:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operacao', 'Operacao'), ('cenografia', 'Cenografia'), ('coreografia', 'Coreografia'), ('criacao', 'Criação'), ('desenho-luz', 'Desenho de Luz'), ('desenho-som', 'Desenho de Som'), ('direcao', 'Direção'), ('direcao-production', 'Direção de Produção'), ('interpretacao', 'Interpretação'), ('assistente-direcao', 'Assistente de Direcão')], max_length=50)),
                ('weight', models.PositiveSmallIntegerField(blank=True, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ('production', 'weight', 'person'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('biosketch', ckeditor.fields.RichTextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('place', mapbox_location_field.models.LocationField(map_attrs={}, verbose_name='Local')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staging', models.BooleanField(blank=True, verbose_name='Em cena')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Baseado no conto de | Sobre piolhos e actores | A verdadeira historia d...', max_length=255, verbose_name='Sub-título')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('video', models.URLField(help_text='youtube, vimeo, etc', verbose_name='Vídeo')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Duração')),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Autores')),
                ('genre', models.CharField(blank=True, choices=[('performance', 'Performance'), ('theatre', 'Teatro'), ('dance', 'Dança'), ('dance-theatre', 'Dança-teatro'), ('theatre-dance', 'Teatro-dança')], max_length=2, null=True, verbose_name='Género')),
                ('synopsys', ckeditor.fields.RichTextField(blank=True, verbose_name='Sinopse')),
                ('credits', models.ManyToManyField(through='production.Participation', to='production.Person', verbose_name='Ficha Técnica')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galeria')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Producões',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
                ('video', models.URLField(help_text='youtube, vimeo, etc')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Place')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='production.Production')),
            ],
            options={
                'verbose_name': 'Apresetação',
                'verbose_name_plural': 'Apresentações',
                'ordering': ('-date_time',),
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Person'),
        ),
        migrations.AddField(
            model_name='participation',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Production'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('synopsys', ckeditor.fields.RichTextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Event')),
            ],
            options={
                'verbose_name': 'Evento',
                'ordering': ('date_time', 'title'),
            },
        ),
    ]
