# Generated by Django 2.2.10 on 2020-02-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('-date_time',), 'verbose_name': 'Apresentação', 'verbose_name_plural': 'Apresentações'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video',
            field=models.URLField(blank=True, help_text='youtube, vimeo, etc'),
        ),
        migrations.AlterField(
            model_name='production',
            name='video',
            field=models.URLField(blank=True, help_text='youtube, vimeo, etc', verbose_name='Vídeo'),
        ),
    ]
