# Generated by Django 2.2.10 on 2020-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200209_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='genre',
            field=models.CharField(blank=True, choices=[('performance', 'Performance'), ('theatre', 'Teatro'), ('dance', 'Dança'), ('dance-theatre', 'Dança-teatro'), ('theatre-dance', 'Teatro-dança')], max_length=20, null=True, verbose_name='Género'),
        ),
    ]
