# Generated by Django 2.2.10 on 2020-02-09 23:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200209_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ('-is_staging', '-presentations__date_time'), 'verbose_name': 'Produção', 'verbose_name_plural': 'Producões'},
        ),
        migrations.AddField(
            model_name='production',
            name='leading',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
    ]
