# Generated by Django 2.2.10 on 2020-02-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_event_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_time', 'title'), 'verbose_name': 'Evento'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('concerto', 'Concerto'), ('conferencia', 'Conferência'), ('exposicao', 'Exposição'), ('instalacao', 'Instalação'), ('performance', 'Performance')], max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('criacao', 'Criação'), ('direcao', 'Direção'), ('assistente-direcao', 'Assistente de Direção'), ('coreografia', 'Coreografia'), ('cenografia', 'Cenografia'), ('desenho-luz', 'Desenho de Luz'), ('desenho-som', 'Desenho de Som'), ('operacao', 'Operacao'), ('interpretacao', 'Interpretação'), ('direcao-production', 'Direção de Produção')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participation',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Índice para ordenação em elenco', verbose_name='Weight'),
        ),
    ]
