# Generated by Django 2.2.10 on 2020-02-10 20:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('production', '0006_auto_20200210_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galeria'),
        ),
        migrations.AddField(
            model_name='event',
            name='leading',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.URLField(blank=True, help_text='youtube, vimeo, etc', verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='synopsys',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Sinopse'),
        ),
    ]
