# Generated by Django 2.2.10 on 2020-02-09 00:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, help_text='Os artigos mais leves flutuam, os mais pesados afundam', verbose_name='Peso')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Destaque')),
                ('menu', models.CharField(blank=True, choices=[('top', 'Todo'), ('bottom', 'Rodapé'), ('sidebar', 'Lateral')], max_length=10)),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('short_title', models.CharField(blank=True, help_text='Que aparece em listas. Reverte para as 3 primeiras palavras do título', max_length=50, verbose_name='Título abrev.')),
                ('body', ckeditor.fields.RichTextField(help_text='Em caso de Copy+Paste, <b>copiar sempre de texto simples</b> e não directamente do `Word` ou da Internet', verbose_name='Text')),
                ('slug', models.SlugField(blank=True, max_length=192)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('edited_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='Imagem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Article', verbose_name='Ascendente')),
            ],
            options={
                'verbose_name': 'Artigo',
                'ordering': ('weight', 'title'),
            },
        ),
    ]
